language: objective-c
osx_image: xcode12
before_install:
  - gem install cocoapods -v '1.8.3'
install:
  - ./install_swiftlint.sh
script:
  - gem install travis
  - travis lint .travis.yml --no-interactive
  - swiftlint
  - xcodebuild clean build test -workspace Example/FlexibleRowHeightGridLayout.xcworkspace -scheme FlexibleRowHeightGridLayout-Example -destination "platform=iOS Simulator,name=iPhone 11 Pro" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint --allow-warnings
